Feature/home screen
JvnSlv/ToDo-RxBloc pull request #10
Opened 2023-01-09 08:25 UTC by JvnSlv

2023-01-09 08:31 UTC, StanevPrime requested changes

2023-01-09 08:31 UTC, StanevPrime commented on lib/feature_todos_list/views/todos_list_page.dart
> +        child: const Icon(Icons.add),
Please use the design system

2023-01-09 08:31 UTC, StanevPrime commented on lib/feature_todos_list/views/todos_list_page.dart
> +        title: const Text('List of todos'),
Please localise you strings

2023-01-09 08:31 UTC, StanevPrime commented on lib/feature_homepage/views/home_page.dart
> +          physics: const NeverScrollableScrollPhysics(),
Please use the https://pub.dev/documentation/go_router/latest/go_router/ShellRoute-class.html

2023-01-09 08:31 UTC, StanevPrime commented on pubspec.yaml
> +  todos_app_core:
Please use a mono-repo. In other words there is no need of two repos for this project you can use the original one only

2023-01-10 13:36 UTC, StanevPrime requested changes

2023-01-10 13:36 UTC, StanevPrime commented on lib/feature_homepage/bloc/home_bloc.dart
> +abstract class HomeBlocEvents {
For the next task I believe you will need to extent this class in a way that it will hold other data than the selected page so I would suggest making it more generic. Renaming this class to NavigationBloc is a good start, since later when you work on task edit/details you can pass taskId as a event

2023-01-10 13:36 UTC, StanevPrime commented on lib/feature_homepage/bloc/home_bloc.dart
> +  void setPageIndex(int pageIndex);
I believe passing an enum here is a better choice so that it's more clear what means 0, 1 etc

2023-01-10 13:36 UTC, StanevPrime commented on lib/feature_homepage/bloc/home_bloc.dart
> +  Stream<int> get getPageIndex;
Same as above

2023-01-10 13:36 UTC, StanevPrime commented on lib/feature_homepage/views/home_page.dart
> +        context.go(TodoConstants.listRoute);
Please try to navigate from the business layer only.

2023-01-10 13:36 UTC, StanevPrime commented on lib/feature_homepage/views/home_page.dart
> +                      label: 'Home',
Please do not hard code strings in the UI layer, you can use the translation system instead

2023-01-10 13:36 UTC, StanevPrime commented on lib/feature_homepage/views/home_page.dart
> +                      label: 'Stats',
Please do not hard code strings in the UI layer, you can use the translation system instead

2023-01-11 09:26 UTC, StanevPrime requested changes

2023-01-11 09:26 UTC, StanevPrime commented on lib/feature_homepage/bloc/navigation_bloc.dart
> +  final _router = goRouter;
Please use explicit dependency injection if possible

2023-01-11 09:26 UTC, StanevPrime commented on lib/feature_homepage/views/home_page.dart
> +          return Scaffold(
I guess you can use an expression body here

2023-01-11 09:26 UTC, StanevPrime commented on lib/feature_homepage/views/home_page.dart
> +              iconSize: 25,
Please do not hard code any sizes in the UI Layer, use the spacing from the design system for that

2023-01-11 09:28 UTC, StanevPrime commented on lib/feature_homepage/bloc/navigation_bloc.dart
> +          _router.go(TodoConstants.listRoute);
Can we use go_router_bulder here for generating the location of the route ?

2023-01-11 10:17 UTC, JvnSlv commented on lib/feature_homepage/bloc/navigation_bloc.dart
> +          _router.go(TodoConstants.listRoute);
I'm not sure if this is possible since go_router_builder is still not supporting shell routes

2023-01-12 09:27 UTC, StanevPrime commented on lib/base/theme/design_system/design_system_typography.dart
> +  final double navIconSize = 25;
All sizes should resides into a spacing class. I have created a dedicated ticket for handling this https://github.com/JvnSlv/ToDo-RxBloc/issues/11

2023-01-12 09:28 UTC, StanevPrime approved these changes

2023-01-12 09:29 UTC, merged